---
sudo: required

env:
  # tests/test.yml
  - repository: geerlingguy/docker-centos7-ansible
    version: latest
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    site: test.yml
    prefix: ''
    http_port: 8080
  - repository: geerlingguy/docker-ubuntu1404-ansible
    version: latest
    init: /sbin/init
    run_opts: ""
    site: test.yml
    prefix: ''
    http_port: 8080
  - repository: geerlingguy/docker-ubuntu1204-ansible
    version: latest
    init: /sbin/init
    run_opts: ""
    site: test.yml
    prefix: ''
    http_port: 8080

  # tests/test-http-port.yml
  - repository: geerlingguy/docker-ubuntu1404-ansible
    version: latest
    init: /sbin/init
    run_opts: ""
    site: test-http-port.yml
    prefix: ''
    http_port: 8081

  # tests/test-prefix.yml
  - repository: geerlingguy/docker-ubuntu1404-ansible
    version: latest
    init: /sbin/init
    run_opts: ""
    site: test-prefix.yml
    prefix: jenkins
    http_port: 8080

  # tests/test-jenkins-version.yml
  - repository: geerlingguy/docker-centos7-ansible
    version: latest
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    site: test-jenkins-version.yml
    prefix: ''
    http_port: 8080
  - repository: geerlingguy/docker-ubuntu1404-ansible
    version: latest
    init: /sbin/init
    run_opts: ""
    site: test-jenkins-version.yml
    prefix: ''
    http_port: 8080

  # tests/test-plugins.yml
  - repository: geerlingguy/docker-ubuntu1404-ansible
    version: latest
    init: /sbin/init
    run_opts: ""
    site: test-plugins.yml
    prefix: ''
    http_port: 8080

  # tests/test-plugins-with-pinning.yml
  - repository: geerlingguy/docker-ubuntu1404-ansible
    version: latest
    init: /sbin/init
    run_opts: ""
    site: test-plugins-with-pinning.yml
    prefix: ''
    http_port: 8080

services:
  - docker

before_install:
  # Pull container
  - 'sudo docker pull ${repository}:${version}'

script:
  - container_id=$(mktemp)
  # Run container in detached state
  - 'sudo docker run --detach --volume="${PWD}":/etc/ansible/roles/role_under_test:ro ${run_opts} ${repository}:${version} "${init}" > "${container_id}"'

  # Install dependencies.
  - 'sudo docker exec "$(cat ${container_id})" ansible-galaxy install -r /etc/ansible/roles/role_under_test/tests/requirements.yml'

  # Ansible syntax check.
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/$site --syntax-check'

  # Test role.
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/$site'

  # Test role idempotence.
  - idempotence=$(mktemp)
  - sudo docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/role_under_test/tests/$site | tee -a ${idempotence}
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Make sure Jenkins is running.
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm curl http://localhost:$http_port/$prefix'

after_failure:
  # Check what happened on systemd systems.
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm systemctl -l status jenkins.service'
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm journalctl -xe --no-pager'

after_success:
  # Clean up
  - 'sudo docker stop "$(cat ${container_id})"'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
