---
- name: Ensure Jenkins repo is installed.
  get_url:
    # LTS repo: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
    url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Add Jenkins repo GPG key.
  rpm_key:
    state: present
    # LTS key: http://pkg.jenkins-ci.org/redhat-stable/jenkins-ci.org.key
    key: http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key

- name: Ensure Jenkins is installed.
  yum: pkg=jenkins state=installed

- name: Ensure Jenkins is started and runs on startup.
  service: name=jenkins state=started enabled=yes

- name: Wait for Jenkins to start up before proceeding.
  wait_for:
    host: "{{ hostname }}"
    port: 8080
    timeout: 300

- name: Get the jenkins-cli jarfile from the Jenkins server.
  get_url:
    url: "http://{{ hostname }}:8080/jnlpJars/jenkins-cli.jar"
    dest: "{{ jenkins_jar_location }}"
  register: jarfile_get
  until: "'OK' in jarfile_get.msg or 'file already exists' in jarfile_get.msg"
  retries: 5
  delay: 10

# Update Jenkins and install configured plugins.
- include: plugins.yml
