---
- name: Ensure dependencies are installed.
  yum: pkg=curl state=installed

- name: Ensure Jenkins LTS repo is installed.
  get_url:
    url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
  when: jenkins_use_lts

- name: Ensure Jenkins repo is installed.
  get_url:
    url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
  when: not jenkins_use_lts

- name: Add Jenkins LTS repo GPG key.
  rpm_key:
    state: present
    key: http://pkg.jenkins-ci.org/redhat-stable/jenkins-ci.org.key
  when: jenkins_use_lts

- name: Add Jenkins repo GPG key.
  rpm_key:
    state: present
    key: http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
  when: not jenkins_use_lts

- name: Ensure Jenkins is installed.
  yum: pkg=jenkins state=installed
