---
- name: Converge
  hosts: all
  become: true

  vars:
    jenkins_url_prefix: /jenkins

  pre_tasks:
    - include_tasks: java-8.yml

  roles:
    - geerlingguy.java
    - geerlingguy.jenkins

  post_tasks:
    - name: Check if Jenkins is running on the specified port.
      uri:
        url: "http://localhost:8080{{ jenkins_url_prefix }}"
